CREATE TABLE public.file (
    id bigint NOT NULL,
    path text NOT NULL,
    parent_id bigint,
    storage_id bigint NOT NULL,
    size bigint NOT NULL,
    name text NOT NULL,
    is_dir boolean NOT NULL,
    is_ready boolean NOT NULL
);

ALTER TABLE public.file OWNER TO postgres;

ALTER TABLE public.file ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.storage (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    capacity bigint NOT NULL
);

ALTER TABLE public.storage OWNER TO postgres;

ALTER TABLE public.storage ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.strorage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.usr (
    id bigint NOT NULL,
    login text NOT NULL,
    password text NOT NULL
);

ALTER TABLE public.usr OWNER TO postgres;

ALTER TABLE public.usr ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usr_id_seq
    START WITH 2
    INCREMENT BY 1
    MINVALUE 2
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.file
    ADD CONSTRAINT file_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.storage
    ADD CONSTRAINT strorage_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.usr
    ADD CONSTRAINT usr_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.usr
    ADD CONSTRAINT usr_unique UNIQUE (login);

ALTER TABLE ONLY public.file
    ADD CONSTRAINT "FK_file_parent_id" FOREIGN KEY (parent_id) REFERENCES public.file(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;

ALTER TABLE ONLY public.file
    ADD CONSTRAINT "FK_storage_storage_id" FOREIGN KEY (storage_id) REFERENCES public.storage(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;

ALTER TABLE ONLY public.storage
    ADD CONSTRAINT "FK_usr_user_id" FOREIGN KEY (user_id) REFERENCES public.usr(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
