--
-- PostgreSQL database dump
--

-- Dumped from database version 14.1 (Debian 14.1-1.pgdg110+1)
-- Dumped by pg_dump version 14.1

-- Started on 2021-12-11 15:35:33 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


ALTER DATABASE network_storage OWNER TO postgres;

\connect network_storage

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 209 (class 1259 OID 16437)
-- Name: file; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.file (
    id bigint NOT NULL,
    path text NOT NULL,
    parent_id bigint,
    storage_id bigint NOT NULL,
    size bigint NOT NULL,
    name text NOT NULL,
    is_dir boolean NOT NULL,
    is_ready boolean NOT NULL
);


ALTER TABLE public.file OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 16442)
-- Name: file_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.file ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 16443)
-- Name: storage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.storage (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    capacity bigint NOT NULL
);


ALTER TABLE public.storage OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 16446)
-- Name: strorage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.storage ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.strorage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 16447)
-- Name: usr; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usr (
    id bigint NOT NULL,
    login text NOT NULL,
    password text NOT NULL
);


ALTER TABLE public.usr OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 16452)
-- Name: usr_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usr ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usr_id_seq
    START WITH 2
    INCREMENT BY 1
    MINVALUE 2
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3178 (class 2606 OID 16454)
-- Name: file file_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.file
    ADD CONSTRAINT file_pkey PRIMARY KEY (id);


--
-- TOC entry 3180 (class 2606 OID 16456)
-- Name: storage strorage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.storage
    ADD CONSTRAINT strorage_pkey PRIMARY KEY (id);


--
-- TOC entry 3182 (class 2606 OID 16458)
-- Name: usr usr_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usr
    ADD CONSTRAINT usr_pkey PRIMARY KEY (id);


--
-- TOC entry 3184 (class 2606 OID 16460)
-- Name: usr usr_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usr
    ADD CONSTRAINT usr_unique UNIQUE (login);


--
-- TOC entry 3185 (class 2606 OID 16461)
-- Name: file FK_file_parent_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.file
    ADD CONSTRAINT "FK_file_parent_id" FOREIGN KEY (parent_id) REFERENCES public.file(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 3186 (class 2606 OID 16466)
-- Name: file FK_storage_storage_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.file
    ADD CONSTRAINT "FK_storage_storage_id" FOREIGN KEY (storage_id) REFERENCES public.storage(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 3187 (class 2606 OID 16471)
-- Name: storage FK_usr_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.storage
    ADD CONSTRAINT "FK_usr_user_id" FOREIGN KEY (user_id) REFERENCES public.usr(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


-- Completed on 2021-12-11 15:35:33 UTC

--
-- PostgreSQL database dump complete
--

